### PR TITLE
Use github actions

### PR DESCRIPTION
**Pull request by samuel-w**
Half of https://github.com/borgbackup/borg/issues/5467
Sample: https://github.com/samuel-w/borg-import/actions/runs/392118282

The 403 is because of my github settings, it works if you grant permissions.

Fixes https://github.com/borgbackup/borg-import/issues/40

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
thanks!

**Comment by ThomasWaldmann** [comment]
looks like it works, great!

**Comment by samuel-w** [comment]
I think the coverage is measuring non-code in its count. Maybe add `source=borg_import` to .coveragerc?

**Comment by ThomasWaldmann** [comment]
yes, but guess it needs to be `source = src/borg_import`.

**Comment by samuel-w** [comment]
It seems to be `source = pkgname` https://github.com/django/django/blob/master/tests/.coveragerc

**Comment by ThomasWaldmann** [comment]
Oh? Then it might be wrong in the `borg` repo (where I looked before writing)... - please double check.

**Comment by samuel-w** [comment]
It seems to take both syntaxes. The reason for the coverage dropping is due to each tox creating its own folder https://codecov.io/gh/borgbackup/borg-import/tree/ef1352064f21b183d57521786c4466c6a3cebea0

**Pull request merged**
